# Python Numpy

### What is Numpy?

- Numpy is basically a ibrary consisting of multidimensional array objects and a collection of routines for processing those arrays. 
- Provides high computing performance.
- Mathematical and logical operations on arrays can be performed. 

### Importing Numpy

In [4]:
import numpy

# or

import numpy as np                  # 'np' an alias of numpy to use it later in the code. 

### Creating an array

In [8]:
#One Dimensional Array
a = np.array([1,2,3])

#Two Dimensional Array
b = np.array([(1,2,3),(4,5,6),(7,8,9)])

In [13]:
a

array([1, 2, 3])

In [14]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Initial Placeholders

In [16]:
# 1D array of length 3 with zeros at all the places 
np.zeros(3)

array([0., 0., 0.])

In [19]:
#2D array of all zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
#3D array of all zeros.
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [24]:
#3X4 array with all values 9
np.full((3,4),9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [25]:
#4X5 array of random floats between 0 and 1
np.random.rand(4,5)

array([[0.07899331, 0.96791233, 0.10321499, 0.98110421, 0.35324334],
       [0.21240449, 0.62062912, 0.50514857, 0.888012  , 0.51650229],
       [0.62561514, 0.42396175, 0.28187568, 0.96514469, 0.20083699],
       [0.64071901, 0.93983903, 0.26870847, 0.92984687, 0.72823202]])

In [26]:
#3X4 array with all values 1
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
#$X4 array of 0 with 1 on diagonal.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.add(a,b)

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])